name: Publicar Release e Fazer Merge

on:
  push:
    tags:
      - 'v1.*'

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true

  merge-branches:
    needs: release
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge release ➜ develop
        shell: bash
        run: |
          git fetch origin
          BRANCH_FROM=$(git tag --points-at HEAD || echo "${GITHUB_REF_NAME}")
          git checkout develop
          git merge origin/$BRANCH_FROM --no-edit || true
          git push origin develop

      - name: Merge develop ➜ master
        shell: bash
        run: |
          git checkout master
          git merge develop --no-edit || true
          git push origin master

      - name: Merge master ➜ main
        shell: bash
        run: |
          git checkout main
          git merge master --no-edit || true
          git push origin main
