name: Atualizar Master e Main a partir da Develop

on:
  push:
    branches:
      - develop

jobs:
  merge-branches:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configurar Git
        shell: pwsh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge develop ➜ master
        shell: pwsh
        run: |
          git fetch origin
          git checkout master
          git merge origin/develop --no-edit
          git push origin master

      - name: Merge master ➜ main
        shell: pwsh
        run: |
          git fetch origin
          git checkout main
          git merge origin/master --no-edit
          git push origin main
